-- MySQL Script generated by MySQL Workbench
-- Thu Apr 25 02:56:26 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`medico` (
  `idmedico` INT NOT NULL AUTO_INCREMENT,
  `imagenPerfil` BLOB NULL,
  `nombre` VARCHAR(45) NULL,
  `materno` VARCHAR(45) NULL,
  `paterno` VARCHAR(45) NULL,
  `cedulaProfesional` VARCHAR(45) NULL,
  PRIMARY KEY (`idmedico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cita` (
  `idCita` INT NOT NULL,
  `nombre` VARCHAR(65) NOT NULL,
  `paterno` VARCHAR(65) NOT NULL,
  `materno` VARCHAR(65) NOT NULL,
  `email` VARCHAR(65) NOT NULL,
  `telefono` VARCHAR(65) NOT NULL,
  `tratamiento` VARCHAR(65) NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `mensaje` VARCHAR(255) NOT NULL,
  `medico_idmedico` INT NOT NULL,
  PRIMARY KEY (`idCita`),
  INDEX `fk_cita_medico1_idx` (`medico_idmedico` ASC) VISIBLE,
  CONSTRAINT `fk_cita_medico1`
    FOREIGN KEY (`medico_idmedico`)
    REFERENCES `mydb`.`medico` (`idmedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`login` (
  `idlogin` INT NOT NULL,
  `email` VARCHAR(65) NOT NULL,
  `password` VARCHAR(65) NOT NULL,
  `medico_idmedico` INT NOT NULL,
  PRIMARY KEY (`idlogin`),
  INDEX `fk_login_medico_idx` (`medico_idmedico` ASC) VISIBLE,
  CONSTRAINT `fk_login_medico`
    FOREIGN KEY (`medico_idmedico`)
    REFERENCES `mydb`.`medico` (`idmedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
