-- MySQL Script generated by MySQL Workbench
-- Fri Apr 26 04:48:15 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema clinica_dental
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema clinica_dental
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clinica_dental` DEFAULT CHARACTER SET utf8 ;
USE `clinica_dental` ;

-- -----------------------------------------------------
-- Table `clinica_dental`.`medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_dental`.`medico` (
  `idMedico` INT NOT NULL AUTO_INCREMENT,
  `imagenPerfil` VARCHAR(50000) NULL,
  `nombre` VARCHAR(65) NOT NULL,
  `paterno` VARCHAR(65) NOT NULL,
  `materno` VARCHAR(65) NOT NULL,
  `especialidad` VARCHAR(65) NOT NULL,
  `cedulaProfesional` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMedico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_dental`.`cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_dental`.`cita` (
  `idCita` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(65) NOT NULL,
  `paterno` VARCHAR(65) NOT NULL,
  `materno` VARCHAR(65) NOT NULL,
  `email` VARCHAR(65) NULL,
  `telefono` VARCHAR(65) NOT NULL,
  `tratamiento` VARCHAR(45) NOT NULL,
  `fecha` VARCHAR(65) NOT NULL,
  `hora` VARCHAR(65) NOT NULL,
  `mensaje` VARCHAR(65) NULL,
  `medico_idMedico` INT NOT NULL,
  PRIMARY KEY (`idCita`),
  INDEX `fk_cita_medico1_idx` (`medico_idMedico` ASC) ,
  CONSTRAINT `fk_cita_medico1`
    FOREIGN KEY (`medico_idMedico`)
    REFERENCES `clinica_dental`.`medico` (`idMedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_dental`.`sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_dental`.`sucursal` (
  `idSucursal` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(65) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(105) NOT NULL,
  `colonia` VARCHAR(65) NOT NULL,
  `medico_idMedico` INT NOT NULL,
  PRIMARY KEY (`idSucursal`),
  INDEX `fk_sucursal_medico1_idx` (`medico_idMedico` ASC) ,
  CONSTRAINT `fk_sucursal_medico1`
    FOREIGN KEY (`medico_idMedico`)
    REFERENCES `clinica_dental`.`medico` (`idMedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_dental`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_dental`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(65) NOT NULL,
  `email` VARCHAR(65) NOT NULL,
  `password` VARCHAR(65) NOT NULL,
  `medico_idMedico` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_usuario_medico_idx` (`medico_idMedico` ASC) ,
  CONSTRAINT `fk_usuario_medico`
    FOREIGN KEY (`medico_idMedico`)
    REFERENCES `clinica_dental`.`medico` (`idMedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
